fix ui-test (#73)
`npx @puppeteer/browsers install chrome@stable` is failing with:

Error: All providers failed for chrome 150.0.7871.24:
  - DefaultProvider: Extraction failed: Required native binary ('tar.exe', 'powershell.exe', 'pwsh.exe' or 'unzip') was not found in the system PATH.
    at installWithProviders (file:///home/build/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/install.js:108:11)
    at async install (file:///home/build/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/install.js:118:12)
    at async #install (file:///home/build/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/CLI.js:392:9)
    at async Object.handler (file:///home/build/.npm/_npx/c99440fc2d0a3f00/node_modules/@puppeteer/browsers/lib/CLI.js:196:17)

This may be a bug in the package but if giving it unzip makes it happy
then let's give it unzip.